#!/bin/bash
url=$1
errorsqli=$2
httpx=$3
for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "error" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlierror.txt
for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "error" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqlierror.txt

for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "column" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlicolumn.txt
for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "column" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqlicolumn.txt

for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "table" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlitable.txt
for i in $(cat $1);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i/FUZZ -w $2 -mr "table" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqtable.txt

for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "error" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlierrorheader.txt
for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "error" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqlierrorheader.txt

for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "column" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlicolumnheader.txt
for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "column" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqlicolumnheader.txt

for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "table" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_sqlitableheader.txt
for i in $(cat $3);do echo "
==========================================================
URL: $i
==========================================================
">>ffuf_op.txt| ffuf -u $i -w $2 -mr "table" -H "Accept: FUZZ" -H "Accept-Charset: FUZZ" -H "Accept-Encoding: FUZZ" -H "Accept-Language: FUZZ" -H "Authorization: FUZZ" -H "Cookie: FUZZ" -H "Host: FUZZ" -H "If-Modified-Since: FUZZ" -H "Referer: FUZZ" -H "User-Agent: FUZZ" -X POST -t 60 -s -H "Content-Type: application/x-www-form-urlencoded" ;done| tee -a ffuf_op_post_method_sqtableheader.txt


